openapi: 3.0.1
info:
  title: Test API Telefonica
  contact:
    name: Víctor Moreno Zapata
    email: morenovictorzapata@gmail.com
  version: Api V1
servers:
- url: http://localhost:8091
  description: Generated server url
paths:
  /customer:
    get:
      tags:
      - customer-controller
      operationId: list
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - customer-controller
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerEntity'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /customer/paginate:
    post:
      tags:
      - customer-controller
      operationId: paginate
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /customer/list-by-offer-date:
    post:
      tags:
      - customer-controller
      operationId: listByOfferDate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
                format: date-time
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /customer/list-by-document-number-and-document-type:
    post:
      tags:
      - customer-controller
      operationId: listByDocumentNumberAndDocumentType
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /customer/{id}:
    get:
      tags:
      - customer-controller
      operationId: getById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    patch:
      tags:
      - customer-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    CustomerEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fullName:
          type: string
        documentType:
          type: string
        documentNumber:
          type: string
        birthdayDate:
          type: string
          format: date-time
        mobileLines:
          type: array
          items:
            $ref: '#/components/schemas/MobileLineEntity'
    MobileLineEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        phoneNumber:
          type: string
        lineStatus:
          type: boolean
        lineType:
          type: string
        plan:
          $ref: '#/components/schemas/PlanEntity'
        customer:
          $ref: '#/components/schemas/CustomerEntity'
        mobileLineOffers:
          type: array
          items:
            $ref: '#/components/schemas/MobileLineOfferEntity'
    MobileLineOfferEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        mobileLine:
          $ref: '#/components/schemas/MobileLineEntity'
        offer:
          $ref: '#/components/schemas/OfferEntity'
    OfferEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        description:
          type: string
        validFrom:
          type: string
          format: date-time
        validTo:
          type: string
          format: date-time
    PlanEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
